name: Build ISO Installer

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-iso:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git golang go-md2man qemu-utils \
            podman make

      - name: Clone bootc-image-builder
        run: |
          git clone https://github.com/containers/bootc-image-builder.git
          cd bootc-image-builder
          make build

      - name: Build ISO
        run: |
          sudo ./bootc-image-builder/bin/bootc-image-builder \
            --type iso \
            --config disk_config/iso-kde.toml \
            --output-dir output \
            ghcr.io/${{ github.repository_owner }}/cosmic-gaming-don:latest

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: cosmic-gaming-don-iso
          path: output/*.iso
