name: Build ISO Installer

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: read

jobs:
  build-iso:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install required packages
        run: |
          sudo apt update
          sudo apt install -y qemu-utils podman

      - name: Login podman to GHCR
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | sudo podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Prepare output dir
        run: mkdir -p output

      - name: Build ISO
        run: |
          sudo podman run --rm --privileged \
            -v ${{ github.workspace }}:/workspace \
            -v ${{ github.workspace }}/output:/output \
            ghcr.io/containers/bootc-image-builder:latest \
            --type iso \
            --config /workspace/disk_config/iso-kde.toml \
            ghcr.io/${{ github.repository_owner }}/cosmic-gaming-don:latest

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: cosmic-gaming-don-iso
          path: output/*.iso
